### ISSUE TITLE
Electrum - send error but assets sent as expected

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/cb-client-wallet#87] opened 2019-08-15 14:43 UTC
Electrum wallet with imported private keys for inflation and fees. Transactions already consolidated so no size based restriction or issue. Send tx, signed & broadcasted as expected but an error appeared around the time the tx was received. Having checked querywhitelist the address shouldn't have accepted the transaction as query whitelist address returned false?!

<img width="1680" alt="Screenshot 2019-08-15 at 15 39 22" src="https://user-images.githubusercontent.com/31970407/63102456-1ec6cc80-bf73-11e9-85e8-e306de393129.png">

**Comment by nkostoulas** [comment] 2019-08-19 10:46
@lawlawlaw @AstryX any ideas?

**Comment by AstryX** [comment] 2019-08-19 13:46
@nkostoulas not sufficient information, i think we would need to try and recreate this issue. From what I see there is unconfirmed amount which represents the fee. I suspect that the logic when parsing transactions that are sent to addresses that are both ismine=true could be a little different than a standard transaction to address from one wallet to another (just guessing). Additionally, since it is yet to be confirmed it could have been added to the mempool but rejected by the whitelisting node.

**Comment by lawlawlaw** [comment] 2019-08-19 14:41
This is because whitelist asset has been paid to the fees address in the form of a fee output, and fee outputs do not have a script. I have pushed a fix to "debug" branch.

**Closed** 2019-08-19 15:17 UTC
Labels: bug, priority
